formatter: markdown table

header-from: header.md

sections:
  show:
    - header
    - requirements
    - providers
    - resources
    - inputs
    - outputs

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  anchor: true
  color: true
  escape: true
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true

sort:
  enabled: true
  by: required
